virtualmachine = "myVirtualMachine"
location = "East US"

virtualnetwork = "virtual_network"
subnet = "subnet"
interface = "interface"
ip_name = "ip_name"
securitygrp = "security_group"
securityrule = "security_rule"
linuxm = "linuxmachine"